### ISSUE TITLE
How to force rtags to recognize the *.c files as CXX source

### ISSUE THREAD

**Issue by skt041959** [Andersbakken/rtags#1002]
### Please mark appropriate
 - [x] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description
I have tried to pass the `-x c++ -std=c++11` arguments to rdm's `--default-argument` option. 
But it doesn't work.

#### Expected behavior
The  `-x c++ -std=c++11` arguments added to `--default-argument` will force the rtags recognize *.c files as CXX sources

#### Actual behavior
It still can't read CXX sources and reports such as "unknown type name 'namespace'"

### Environment
- Your operating system: Linux RH55

- LLVM/Clang version:  clang-3.9

**Comment by Andersbakken** [comment]
I think the issue is that the argument parsing falls apart when you pass stuff to --default-arguments without using =

This works for me:

rdm --default-argument=-x --default-argument=c++

It seems like a better idea to add these arguments when indexing the file though.

E.g.

rc -c c++ -x c++ foo.c

Anders
