### ISSUE TITLE
Copy project database from one machine to another (what is fileids)

### ISSUE THREAD

**Issue by sergei-dyshel** [Andersbakken/rtags#1084]
My situation: I have a pretty large project which I'm editing on my local laptop and compile on remote machine. 
My flow requires me to frequently checkout different branches each time reindexing entire project by `rdm`, which takes a lot of time on my laptop. Since remote machine has much more power available for compilation , I thought of the following trick: index files on remote machine and then copy respective directory to `$HOME/.cache/rtags`. The project path is identical on both machines so I guess it should work well but there is also this `fileids` file in `$HOME/.cache/rtags` which is different on remote and local machines. 

How is important this file? Can I just skip it and it will be somehow fixed/rebuilt on local machine? Are there any other obstacles to my plan?

**Comment by pengpengxp** [comment]
I meet the same situation!

I have tried to index linux kernel on my server. And then copy the all cache file to my desktop. But when I use `rc -w' . I can not find the project. Of course, rtags not work correctly.

Is there anybody know how to use the exists cache to reindex the project?

**Comment by JohnC32** [comment]
There is a --sandbox-root option which makes the paths relative and enables copying of the index database. The scenario sounds similar to what you describe. Index the project using --sandbox-root on one system (and also specify a .rtags-config containing 'project: SBROOT'), then you can copy the area and re-use the index. Here's a test:

https://github.com/Andersbakken/rtags/blob/master/tests/sbroot/sbroot_test_help.md

**Comment by pengpengxp** [comment]
It works now. Thank you very much. @JohnC32

**Comment by pengpengxp** [comment]
@JohnC32 But,  I still meet some problems.

I put the index file in ```~/.rtags/rtags_db```, and use rdm on my powerful server as follow:
```
rdm --socket-file=~/.rtags/rdm_socket  --data-dir=~/.rtags/rtags_db/ --log-file=~/.rtags/rtags.log --crash-dump-file=crash_dump.txt --job-count=4 --watch-sources-only --sandbox-root=~/
```

Firstly, index the project as ```rc -J .``` in the top directory of linux-stable project.

Secondly I copy the indexed files  ```~/.rtags/rtags_db/[[SBROOT]]github_linux-stable_```  to  my laptop's directory ```~/.rtags/rtags_db/```.

 After that, ```rc -w``` command do not show the project. So I try to restart the rdm server as follow:

```rc -w```  do not show any project! Even all of the previous project is lost too! 

I find rdm will not restore my project after restart.  

It boring me a lot. Can you do me a favor?

**Comment by JohnC32** [comment]
There are some concepts that I think are relevant here: (1) the absolute path to files (2) the location of the project root and (3) the number of instances of the rdm server. 

The --sandbox-root=DIR option lets you have relative paths. For example, suppose on your server, you have /team/projects/kernel and under the kernel directory you have lots of modules. If you index on your server without the --sandbox-root=DIR option, the paths in the RTags index database will be absolute. If you copy /team/project/kernel to /my/projects/kernel the pre-generated index database will incorrect. To address this you would generate the database on the server using -sandbox-root=/team/project/kernel. You should also place "project: /team/project/kernel" in /team/project/kernel/.rtags-config to ensure RTags treats all files under /team/project/kernel as a single project and not multiple projects. When you create /my/projects/kernel the .rtags-config should contain "project: /my/projects/kerenel".

I've struggled to understand what a project root is in RTags. It isn't well doc'd. As I see it, a project root is a fundamental concept in RTags. All files within a project root are cross-referenced and live in one conceptual "database". For example, you can have a set of modules (.so's) in a project and a cpp file in one module can reference symbols from another module. RTags will attempt to locate the project root using a number of heuristics. Looking at src/RTags.cpp, findProjectRoot(), we see there are two basic              ways RTags locates the project root, 

1. .rtags-config. RTags looks for .rtags-config containing 'project: /path/to/root' in current directory or a parent directory.

2. An anchor file. RTags looks for a project "anchor" file, e.g. ".projectile", ".git", ...

If found that I need to use the .rtags-config file to ensure RTags gets the project root correct.

The number of rdm processes (servers) is also an important concept. A given rdm server can index one or more project. One large code bases, I've found it best to have one rdm server pre-project. To have multiple rdm servers, you use the --socket-file=/path/to/rdm_socket option. You may need to switch to using the --socket-file option, though this requires setting it up in rtags.el.

If you have the same paths on your server where you index the project and on your laptop, then --sandbox-root option is not needed. I suspect you are loosing the other indexed projects because there's no way to pick "project indices" from the overall index database.

I suspect you should be able to get your scenario working. I'm generating RTag indices on relatively large (multi-million C++ line) project and copying the index to other locations. We are using the --sandbox-root option because the location of the copied project is different (has a different absolute path). We are also using --socket-file option to scope one rdm server to one project.

If you give me more details on what you are doing (all the commands that you run including the kernel git clone, etc.), I may be able to spot where things are going wrong.

**Comment by pengpengxp** [comment]
Thank you for your paitient. 

When I use one rdm server for only one project. After copying the indexed file to my lattop, `rc -w' can work after I call `rc -J .' to index the specified project. Because I have copied the project, `rc -J .' will not actual reindex, so it will finish soon. It is exactly want I want.

Here is all my commands:

On my server:

start rdm server :
```
    rdm --socket-file=~/.rtags/rdm_socket \
        --no-rc                           \
        --data-dir=~/.rtags/rtags_db      \
        --log-file=~/.rtags/rtags.log     \
        --crash-dump-file=crash_dump.txt  \
        --job-count=12                    \
        --watch-sources-only              \
        --sandbox-root=~/ 
```
cd to project and index it:
```
cd ~/github/linux-stable
rc --socket-file ~/.rtags/rdm_socket -J .
```

On my latop:

sync the indexed file:
```
cd ~
mkdir -p .rtags/rtags_db
rsync -az myserver:~/.rtags/ ./
```

start the server(use the same command on my server):
```
    rdm --socket-file=~/.rtags/rdm_socket \
        --no-rc                           \
        --data-dir=~/.rtags/rtags_db      \
        --log-file=~/.rtags/rtags.log     \
        --crash-dump-file=crash_dump.txt  \
        --job-count=12                    \
        --watch-sources-only              \
        --sandbox-root=~/ 
```

now, In the log file `~/.rtags/rtags.log':
```
Running with 12 jobs, using args: -ferror-limit=50 -Wall -fspell-checking -Wno-unknown-warning-option
Can't restore project /home/pengpengxp/github_linux-stable
```

```rc --socket-file ~/.rtags/linux-stable/.rtags/rdm_socket -w ``` show nothing.

Then,  I need to cd to my project and run command to index the project (This command is running on my laptop):
```
cd ~/github/linux-stable
rc --socket-file ~/.rtags/rdm_socket -J .
```

It will finished soon. Log file record:
```
Restoring /home/pengpengxp/github/linux-stable/ ...............................................................................................................................................................................................
```


Now, it can be worked for me.

Although it still don't restore this project after restarting, it doesn't matter. I can use rtags to jump in linux kernel now. Thank you so much.

And my last question is: if I have multi project need this procedure above, can I put all of the indexed file into one directory? Or must I create a .rtags directory for each project.

**Comment by myrgy** [comment]
Guys, could you please add this hints to README? It's very useful!

**Comment by JohnC32** [comment]
I'll try to put something together to describe how to copy the database along with an example.
