### ISSUE TITLE
General question about rtags-diagnostics and reindex

### ISSUE THREAD

**Issue by zhihuiFan** [Andersbakken/rtags#1210]
Thanks for the awesome projects!

I start to use rtags for big project codeing now and I also read some issue here before this asking.  Now I still have the following questions I want to make it clear so that I can use it more effectively. 

1.  Rtags-diagnostics 

Let’s say I have error on line 100 first, and it reports me something wrong,  after I fix it, it still there for some time. 
Questions:  
a).  is it use the similar logic of “rtags-compile-file” to know if there is an error or not?
b).  After the code fix,  how long time does rtags need to recheck & refresh the diagnostics info?

2.  Reindex.

   a).  Ctags can index all the files in 1 minute, while rtags needs 40 minutes for the same project.   Is it fair to compare the 2?  What is the benefits of the long time indexing? 

  b).  Suppose file dependency like this.  A <-B <-C 
        If I modified C,  will A and B reindexed?  If yes,  I triggered an reindex because of C and it needs some time.  What if I changed C again during the last round of indexing? Will it reindex A and B again? 
        Shall I suspend the index in the active changes of C and un-suspend after that?

  c).  I’m working with MongoDB project and in its repo, there are many 3rd party libraries  in the same repo. I never touch the third-party files, but they are reindex as well some time.  So if a file whose included header files doesn’t change,  suppose it should not be reindexed?  what may be the reason for my reindexing?

Thanks

**Comment by zhihuiFan** [comment]
Let me try to answer my question by myself.

1.a).  suppose same
1.b).  the recheck happens when a).  the changes has been saved   b). the file is not suspend.  suppose the rtags should be able to refresh after the file save.

2.a).  still not clear so far.
2.b).  
>> If I modified C, will A and B reindexed? 

Yes. 

>> What if I changed C again during the last round of indexing?  Will it reindex A and B again?

Yes.  C usually is a header file, try to minimize the changes of a header file. like a). define the interface carefully  b). put the implementation into .cc file rather than in the header file.   c).  Just save the file when you are confident.

2.c).  If happens rarely,   but I still doesn't know how to catch the reason.

**Comment by Andersbakken** [comment]
Hi

Sorry about the delay. 

The diagnostics are produced by clang so we need a full reindex from clang to refresh the list. I suppose we could manually try to infer that it will go away if the line was changed from emacs but this is sorta not the general approach of rtags. The elisp knows generally little about the c++ parser. 

If you trigger another reindex while indexing one or more files we will cancel the first one and start again. 

ctags is a simple parser that looks for words that seem relevant to c and c++. RTags, since it uses clang is a fully featured compiler so there's really no room to compare. For sure there are times when the overhead of rtags isn't worth it and ctags (gtags is better IMO) or grep is a more useful tool. 

I can't quite see how 2c would happen if the 3rdparty headers aren't including any generated headers or something like that. Maybe your build system regenerates some config.h file or something?

**Comment by zhihuiFan** [comment]
Thanks @Andersbakken for your time & answer!   I will check if it is something like "config.h" in 3rd party resource.   All the questions are clear now~
