### ISSUE TITLE
rtags.el keymap prefix change proposal

### ISSUE THREAD

**Issue by jmataraz** [Andersbakken/rtags#235]
I'd like to propose changing the default prefix key for rtags commands to "\C-cr" instead of "\C-xr". The latter is already used by the rectangle command set, which is, by default, enabled in Emacs. "\C-c" is another common command prefix, but I don't believe is bound to anything common with the "r" suffix.

On a second point, I've found these additions to the keymap very helpful:

```lisp
    (define-key map (concat prefix "k") (function rtags-close-window))
    (define-key map (concat prefix "n") (function rtags-next-match)) ; use stack-back to go to previous matches
```
where 

```lisp
;;;###autoload
(defun rtags-close-window ()
  (interactive)
  (delete-windows-on rtags-buffer-name t))
```

Thus, using the old prefix, "\C-xr k" evaluates to kill-rectangle. I guess, alternatively, you could keep the old prefix and change "k" to "q", which isn't bound under "\C-xr".

**Comment by Andersbakken** [comment]
Sorry about the delay. I'm a little worried about changing the default since it's been like that for almost 3 years and people might be used to it. Generally C-c would have been a better choice. You can set your own prefix however so if you do this:
(rtags-enable-standard-keybindings nil "\C-cr")

It should do the right thing. I believe we don't currently have any keybindings that collide with the standard C-x r bindings.
