### ISSUE TITLE
rtags parse a directory? 

### ISSUE THREAD

**Issue by MichaelLiuzzi** [Andersbakken/rtags#327]
Is there anyway to have rtags parse a directory for source files? 
I can't get visual studio to output build commands so I don't see any other way...?

**Comment by pradhanpk** [comment]
+1. I have a similar issue with my codebase at work. There are times when I just want to get a repo indexed by rtags that I am not using yet - perhaps I just don't know enough about my build tools to know how to generate and modify the compilation database accordingly. However, could you allow a default specification of compile flags and the ability to have `rdm` parse a bunch of files according to these default flags?

**Comment by pradhanpk** [comment]
@MichaelLiuzzi Here's my poor man's elisp helper function for this:

```
(defun my/rtags-default-index-directory (directory-name)
  "Index all files in DIRECTORY-NAME with the default compilation arguments"
  (interactive "DDirectory: ")
  (save-excursion
    (cd rtags-default-directory)
    (message "Generating a list of files in %s..." directory-name)
    (let* ((header-and-source-files (default-shell-command-to-list (concat "ack -f --cpp " directory-name)))
           (my/rc-args-prefix (concat "-c " rtags-default-compiler " -c "))
           (my/rc-args-suffix (concat " " rtags-default-compilation-flags)))
      (mapc
       (λ (file-name) (rtags-call-rc (concat my/rc-args-prefix file-name my/rc-args-suffix)))
       header-and-source-files))))
```

I define the `rtags-default*` variables using a `.dir-locals.el` file. Obviously, this is very inefficient since all the `rc` calls should be done asynchronously and not through elisp. Even better would be adding this as an `rdm` primitive. However, posted the above just in case this temporary solution serves for you.

**Comment by MichaelLiuzzi** [comment]
Hey @pradhanpk !

Thanks for the assist. I'll give it a go. I was thinking of abandoning rtags all together and going with gnu global + helm. Have you seen this <http://tuhdo.github.io/c-ide.html ?

**Comment by pradhanpk** [comment]
@MichaelLiuzzi Yes, I used Tuhdo's guide to setup helm, semantic and gtags. However, rtags is superior to semantic + gtags simply because rtags is powered by clang. I fallback to semantic and gtags when dealing with files not indexed by rtags.

**Comment by Andersbakken** [comment]
Hi Guys

Sorry about the delay. We could certainly add a feature to make some sort of best guess at include paths. Let me see if I can hook up something. The problem is that it very soon falls completely apart if one single includepath is missing. One option that you may not be aware of is bear: (https://github.com/rizsotto/Bear).

Basically you do this:

- install bear
- make sure your build is clean (e.g. do a make clean)
- invoke: 
$ bear make
 instead of
$ make

This will generate a compile_commands.json in the same directory. Now you can use this file to tell rtags about the proper defines/includepaths etc. Repeat the steps if you add files or change includepaths/defines.

To use do this:

$ rc -J 

in the same directory that you ran: bear make

**Comment by MichaelLiuzzi** [comment]
I will try that today and see how it goes. Thank you!

**Comment by Andersbakken** [comment]
I added something for this. 

You should now be able to do this:

rc --guess-flags -c file.cpp 

It will look around for what kind of includepaths it thinks it might need. You can add additional args like this:

rc --guess-flags -c foobar.cpp -Dfoobar=1 -I/path/to/something

Hope this helps. Let me know how it works out.

**Comment by Andersbakken** [comment]
I also added an option that can be passed for additional build-roots to scan for includes. 

E.g.
rc --guess-flags -c foobar.cpp -Dfoobar=1 -I/path/to/something --build-root /path/to/build/root

That path will now also be scanned for headers.
