### ISSUE TITLE
Unexpected heuristics used for rc --find-project-build-root

### ISSUE THREAD

**Issue by cahlbin** [Andersbakken/rtags#372]
I'm using rc --find-project-build-root to set the default-directory for my compile command. It's behaviour and heuristics to derive project root is not what can be expected.

My project initially had the following structure:

```
umbrella-project-root/
    my-cpp-project-root/
       Makefile
       src/
```

```
my-cpp-project-root> rc --find-project-build-root .
>> findProjectRoot [/Users/me/umbrella-project-root/my-cpp-project-root] => [/Users/me/umbrella-project-root/my-cpp-project-root]
```

Then I added a Makefile in the umbrella root, i.e.:

```
umbrella-project-root/
    Makefile
    my-cpp-project-root/
       Makefile
       src/
```
which to affect --find-project-build-root as follows:
```
my-cpp-project-root> rc --find-project-build-root .
>> findProjectRoot [/Users/me/umbrella-project-root/my-cpp-project-root] => [/Users/me/umbrella-project-root/]
```

So I'm guessing that the presence of a Makefile is somehow affecting the heuristics to derive the build root? But why is the top-level Makefile taking preceding over a "closer" one?

Feature request: Make this more explicit by for example being able to put an  .rtags_project file anywhere in a tree, and that would point out the project for files.

What do you think?

**Comment by cahlbin** [comment]
FYI, as a workaround, I'm currently using the following elisp function. Feel free to add it and possibly with adjustments (my knowledge in elisp is not so strong) to the rtags emacs bindings.

````
(defun rtags-get-current-build-root ()
  "Get rtags current project build root"
  (interactive)
  (let ((ppath (locate-dominating-file buffer-file-name ".rtagsprojectroot")))
    (if ppath
        ppath
      (with-temp-buffer
        (rtags-call-rc "--find-project-build-root" ".")
        (goto-char (point-min))
        (while (not (eobp))
          (let ((line (buffer-substring-no-properties (point-at-bol) (point-at-eol))))
            (cond ((string-match "^\\(.*\\) => \\[\\(.*\\)\\]$" line)
                   (setq ppath (match-string-no-properties 2 line))
                   (forward-line)))
            )
          ))
      ppath)))
```

**Comment by Andersbakken** [comment]
Hi

Sorry about the delay. Since many projects have recursive Makefiles for each directory it seemed right to pick the one closest to the root. 

E.g.

foobar/Makefile
foobar/src/Makefile
foobar/src/test/Makefile
foobar/src/test/things/Makefile

There is actually a system to override the project root.

You can do something like this:

/path/foo/Makefile
/path/foo/src/desiredRoot/Makefile

If in this case you want the root to be /path/foo/src/desiredRoot/

You can create a file called .rtags-config in the project and override the project root like this:

project: /path/foo/src/desiredRoot/

Can you see if that works for you?
