### ISSUE TITLE
Security?

### ISSUE THREAD

**Issue by egarrulo** [Andersbakken/rtags#376]
Since RTags has a client/server architecture, I wonder if it is vulnerable to the kind of exploit explained in *Is HMAC auth for requests/responses really necessary?* here:

https://github.com/Valloric/ycmd

Thanks for your attention.

**Comment by jhanssen** [comment]
In theory it certainly could, rtags doesn't do any authentication of requests. In practice however it would be hard to exploit since rtags is listening on a unix domain socket as opposed to a tcp socket and afaik (correct me if I'm wrong here) a web browser can't open connections to a unix domain server. That said, I suppose it would be good practice to have a similar mechanism for future proofing or for people running software (like node.js) that can read and execute input from the internet and also open unix domain sockets.

**Comment by egarrulo** [comment]
> afaik (correct me if I'm wrong here)

Unfortunately, I have no idea.  Thanks for the explanation, though.
