### ISSUE TITLE
Forward declarations

### ISSUE THREAD

**Issue by baol** [Andersbakken/rtags#453]
Hi,
Thanks for RTags, it is really amazing (and reasonably easy to setup)!

The only glitch that I have is that sometimes rtags-resolve-symbol-at-point jumps to the forward declaration. Theoretically correct, but not the best experience.

I made a small example to reproduce, when using '.' from line 2 of `header.hh` rtags will jump to line 1 of the same file and will never reach the full declaration.

`CMakeLists.txt`

    cmake_minimum_required (VERSION 2.6)
    project (forwarddecl)
    add_executable(forwarddecl main.cc forwarded.hh header.hh)

`forwarded.hh` 

    struct ForwardDecl {};

`header.hh` 

    struct ForwardDecl;
    struct Local { ForwardDecl* m; };

`main.cc` 

    #include "forwarded.hh"
    #include "header.hh"
    int main()
    {
        Local l;
        l.m = new ForwardDecl;
    }

**Comment by Andersbakken** [comment]
Hi

Thanks.

I believe this actually might have gotten recently fixed. The issue was
that strictly speaking header.hh did not depend on header.hh so it wouldn't
consider header.hh as a possible target for this forward declaration (there
was a system in place for forward declarations but I think it was buggy).

As of 2c13d39aebfe378101a2c67bc40df6c3a8c24fc5 I changed something in the
algorithm that I think made this work. I couldn't reproduce the problem on
current master.

Can you check with current master?

Anders

**Comment by baol** [comment]
Hi,
my last checkout was 10 days ago, the latest master works, thanks!

Is there a way a can contribute an automated test case for this?

**Comment by Andersbakken** [comment]
There is actually.

Mr Gabor Marton was kind enough to contribute a whole automated test suite
in this commit:

https://github.com/Andersbakken/rtags/pull/444

I haven't actually looked carefully into how to write new tests yet but if
you want to have a crack at it it would be appreciated.

Anders

**Comment by baol** [comment]
Are they running in some CI? 
Should be easy to setup drone.io if not!
