### ISSUE TITLE
rtags-ac seems broken

### ISSUE THREAD

**Issue by philippe-grenet** [Andersbakken/rtags#549]
Hello Anders,

After upgrading all packages (including getting the latest tags-20151230.2332), I get an error when starting Emacs with this minimal configuration:

```lisp
(require 'package)
(package-initialize)


(require 'rtags)
(require 'rtags-ac)
```

Upon evaluating the last form, Emacs displays this error:

```
require: Symbol's value as variable is void: rtags
```

This used to work before I think. Unless I am doing something wrong?

**Comment by philippe-grenet** [comment]
Sorry, bad autocorrect above. The error is "require: Symbol's value as variable is void: rtags".

**Comment by toojays** [comment]
I see this everytime I rebuild rtags as well. If I delete ``src/rtags-ac.elc`` after building, it works again. I assume this issue is due to something unusual about my setup - possibly the fact that the emacs in my path (and hence what is being used to byte-compile) is Emacs 24.3.1, but I actually run a more recent Emacs from the emacs-24 branch (24.5.50.1, built 2015-11-02).

**Comment by Andersbakken** [comment]
I think we're doing something nasty with out build shim thing. I was able
to reproduce it one time. Will try to fix.

**Comment by philippe-grenet** [comment]
Thanks guys. John's answer is correct: deleting rtags-ac.elc fixes the problem. So yes it must be a build issue. For the record I use the stock Emacs 24.5.1 for OS X.

**Comment by Andersbakken** [comment]
I believe the melpa install was busted and should be fixed now. Please reopen if you experience this again.
