### ISSUE TITLE
company-rtags fails to complete at point.

### ISSUE THREAD

**Issue by amosbird** [Andersbakken/rtags#573]
I'm using rtags for a while. Navigation works pretty fine. However I couldn't get company working even once. I have followed README carefully. Directly issue `company-complete` gives `No completion found`. rtags version : `v2.0.r990.gccccd8a-1`

**Comment by Andersbakken** [comment]
Can you try the following (first make sure you're fully up-to-date because
I recently changed some completion-related stuff around):

Set all the completion-related stuff to be on (rtags-completion-enabled,
rtags-dianostics, company backends etc)
Go to a location where you think it should be able to complete. Don't type
anything.

E.g.

#include <stdio.h>

int main()
{
<<<<< Cursor here
}

M-x rtags-prepare-completions

Wait a couple of seconds:

In a shell:

rc --dump-completions

This should print a ton of entries. If it doesn't there's something wrong
that we would have to figure out.

Anders

**Comment by amosbird** [comment]
I've double checked the configurations, and `rc --dump-completions` prints a huge result set.

**Comment by Andersbakken** [comment]
Hm. Can you check: C-h v rtags-last-completions <RET>

Failing this, can you put a breakpoint in rtags-parse-diagnostics and see if ever happens?

Anders

**Comment by amosbird** [comment]
`rtags-last-completions` is null after I execute `rtags-prepare-completions`. I have no idea how to debug rtags. Could you give me some hints?

**Comment by amosbird** [comment]
There is no `rtags-parse-diagnostics` in M-x menu, only `rtags-diagnostics`.

**Comment by cslux** [comment]
Hit C-h f rtags-parse-diagnostics.

rtags-parse-diagnostics is non interactive function, so that's why it is
not available with M-x.

To set a breakpoint at this function hit M-x debug-on-entry RET
rtags-parse-diagnostics

Christian

**Comment by amosbird** [comment]
After I set breakpoint at function `rtags-parse-diagnostics`, I got this window pop out.
![](http://i.imgur.com/Zo4eLeX.jpg)
And then the completion works ![](http://i.imgur.com/Sri7nw2.png).
Then it fails ![](http://i.imgur.com/FUM4a7V.jpg). I get `/usr/bin/clang -fsyntax-only -Xclang -code-completion-macros -x c++ -Xclang -code-completion-at=-:70:12 `

**Comment by cslux** [comment]
@amosbird Seems like `company-rtags` is not in the list of `company-backends`, or comes after other backends.

Go to one of the source file and hit `C-h v company-backends RET`, and post the value of "Its value is '(....."
 Also try to directly call `company-rtags` instead of `company-complete`, if this works `company-rtags` is not in the list or is not the first element. 

For me it looks like `company-clang` is in the list before `company-rtags`.

Christian

**Comment by cslux** [comment]
@amosbird The error you posted at the end, comes from the `company-clang` backend I forgot that.

**Comment by amosbird** [comment]
@cslux Thanks! After I disable clang support, completion works fine.

**Comment by cslux** [comment]
@amosbird 

Glad I could help!

Christian
