### ISSUE TITLE
rtags-find-symbol-at-point is confused on boost::asio::ip::udp::v4()

### ISSUE THREAD

**Issue by ville-h** [Andersbakken/rtags#576]
calling rtags-find-symbol-at-point on "v4" takes me to boost::asio::ip::icmp::v4() in icmp.hpp rather than boost::asio::ip::udp::v4() in udp.hpp
```
#include "boost/asio.hpp"


auto main() -> int {
    boost::asio::ip::udp::endpoint server_endpoint{boost::asio::ip::udp::v4(), 2048};
}
```

**Comment by Andersbakken** [comment]
I actually can't quite reproduce this. I'm assuming the . got lost here but
the following:

#include "boost/asio.hpp"

auto main() -> int {
    boost::asio::ip::udp::endpoint
server_endpoint{boost::asio::ip::udp::v4(), 2048};
}

$ rc --current-file=/home/abakken/temp/rtags576/main.cpp --no-color -f
/home/abakken/temp/rtags576/main.cpp:4:74:
/usr/include/boost/asio/ip/udp.hpp:50:14:  static udp v4()

I'm using libboost1.58-dev
rtags: b346257ffe6fedf9a49f8877803037f0b6e44446
and (probably most importantly), clang: libclang-common-3.6-dev

on Ubuntu 15.10.

My best guess would be that the clang version could be to blame.

It's quite likely that this happens because
of rtags-follow-symbol-try-harder which will make rtags.el try again with a
symbolname-matched hit if it fails.

Can you try the following:

rc --dependencies /path/to/main.cpp and see if it actually depends on
udp.hpp?

Anders

**Comment by ville-h** [comment]
Yes it appears to depend on icmp.hpp.

boost 1.60.0
clang 3.7.1
rtags 76bfbf2

**Comment by ville-h** [comment]
Updated to rtags b346257 and it now goes correctly to udp.hpp.

**Comment by Andersbakken** [comment]
Glad to hear.

Anders
