### ISSUE TITLE
Numbered releases?

### ISSUE THREAD

**Issue by apjanke** [Andersbakken/rtags#582]
It would be nice if there were named/numbered releases for this project, so users could know which points in the commit history are stable, download distributions for them instead of cloning the repo, and refer to them by name.

For example, Homebrew requires a named release. It [was using the `v2.0` tag](https://github.com/Homebrew/homebrew/pull/42045), but that seems to have disappeared.

**Comment by Andersbakken** [comment]
Hi 

We don't actually have releases but rather a rolling master branch :-) 

I killed the v2.0 tag mostly because I was worried that people would use it and mistakenly assume it was "the last stable release". I guess we could introduce some sort of releases but traditionally I've just forgotten to mark anything as a release. Homebrew requires a named tag? 

I guess for the time being I could reintroduce it but I don't really like the idea of people staying on older versions very long.

**Comment by adzenith** [comment]
Homebrew used to have a separate repo for [head-only software](https://github.com/Homebrew/homebrew-head-only), but it's been deprecated. Their fear appears to be that dependencies will break when unversioned software is used. [Only versioned software](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#basic-instructions) is allowed now—this can be named tags (Github "releases"), tarballs on a server, or anything else really.

Would you be willing to tag releases every once in a while for this purpose? Or maybe we could start a discussion over on Homebrew?

Otherwise, and for other users coming here in the meantime, you can still install rtags using `brew install --HEAD rtags`.

**Comment by cslux** [comment]
@apjanke @apjanke We have created a tag 2.1 which is almost up to date. 
I'm closing this issue now!

regards,
Christian

**Comment by adzenith** [comment]
Thank you!

**Comment by adzenith** [comment]
I sent a pull request to bring rtags back into Homebrew.

**Comment by Andersbakken** [comment]
Thanks. We'll try to do a "release" every once in a while :-)

Anders

**Comment by adzenith** [comment]
Thanks! I appreciate your being so accommodating :)

**Comment by apjanke** [comment]
Thanks all for your attention to this. It's back up in Homebrew now.

**Comment by Andersbakken** [comment]
Awesome. I'll try to remember to do another release every couple of months
or so.

Anders
