### ISSUE TITLE
rtags company completion SOMETIMES fails to complete at point.

### ISSUE THREAD

**Issue by vibrys** [Andersbakken/rtags#584]
Hallo Anders & RTags Team.

I'm working with fairly large linux/g++/C++11 project.

I'm very happy how rtags performs with each the functionality it provides.
The only thing I'm missing is completion process; ie. completion does NOT ALWAYS work,
that's why I'm not following issue #573.
The problem described by #578 does not persist here either.

As llvm 3.7.1 is released I've decided to go back to `completion' feature.

I'm trying to complete SomeClass member `m_field' of type std::unique_ptr<T>:

```
void SomeClass::someFun()
{
  m_fie       # here candidate is suggested, so I end up with:
  m_field->   # after `->' is put, rdm backend produces following output:
              #   Got completion request for path/to/someClass.cpp:58:12:
              #   No completion results available path/to/someClass.cpp:58:12: 0

  m_field.    # simillar rdm output after putting `.' at the end.

  m_field.get(); #. then just test on finding the definition under point of std::unique_ptr<T>::get() from current function. Works OK.
  m_field->someFun(); #. another test on finding the definition under point of T::someFun() from current function. Works OK.
}
```

I also tested the above case on short C++ file and it ALL works without any problem there.

Both the tests were performed during the same emacs/rdm session run.

My rtags configuration is following:

```
(require 'rtags)
(rtags-enable-standard-keybindings)

(setq rtags-rc-log-enabled t)
(setq rtags-completions-enabled t)

(rtags-diagnostics)

(add-hook 'c++-mode-hook
          (function (lambda ()
                      (setq company-backends '(company-rtags)))))
```

versions used:
llvm 3.7.1, emacs 24.5.1, rtags-ad85fda (~5 days old).

best regards

**Comment by Andersbakken** [comment]
Hi

Completions are a bit of a mystery to me as well I'm afraid. We use the
APIs from libclang but whether it produces usable results or not is
seemingly hard to influence. I don't suppose it's possible to reproduce a
case where it produces no completions (and likely should have) in a smaller
example? Does it never work at that position btw?

Also, can you verify that it works (or doesn't) the same way whether the
file is saved or not? When the file is unsaved we send the contents of your
buffer over to rdm and there could be a bug in that layer.

Anders

**Comment by amosbird** [comment]
@vibrys I have simillar problems too. Completion goes wrong when completing after `somvar.` ![](http://i.imgur.com/Fpdu3Bf.png)
It cannot find fields and methods of the current variable.

**Comment by vibrys** [comment]
> I don't suppose it's possible to reproduce a case where it produces no completions (and likely should have) in a smaller example?
Indeed

> Does it never work at that position btw?
It never works for that place. What is more, working with other objects of the same type in other places of the code, does not produce any results either. This may mean nothing but coincidence of course.

> Also, can you verify that it works (or doesn't) the same way whether the file is saved or not?
No difference in results. Does it mean that clang is the unit that does not complete?

Anders,
could You tell me in a few words what is the state of completion in rtags, I mean if You for example use completion at rtags development and it works as good as code navigation, or You experience some issues due to either rtags or clang code, or maybe You don't have to use completion at all?

best regards.

**Comment by Andersbakken** [comment]
Hi

Sorry about the delay.

I honestly don't use completions myself on a day-to-day basis. Partially
because it's too slow (and the vast majority of this time is spent in
libclang) and partially because I've gotten so used to dabbrev that I don't
really feel like I need context-sensitive completions.

That being said it seems to work well whenever I try it.

We definitely want to make sure it works well though so we would absolutely
appreciate an reproducible example that can reproduce it not working
correctly.

Anders

**Comment by marxin** [comment]
Hello Anders

I did quite some deep analysis how code completion works in your tool and how is done in [YCM](https://github.com/Valloric/YouCompleteMe).

There's a small test-case where I can illustrate differences.

```cpp
#include <stdio.h>
#include <vector>

using namespace std;

class myclass
{
  void foo();
  public:
  void bar();
};

int main()
{
myclass value;
val  // line 16
// ^---- column 4
}
```

## Test 1

```
$ rc --synchronous-completions -l test-case.cpp:16:4 | wc -l
1270
```

YCM on the same character:
```
value
va_list
volatile
_VA_LIST
_VA_LIST_DEFINED
_G_va_list
_IO_va_list
__GNUC_VA_LIST
__need___va_list
_GLIBCXX_HAVE_ATAN2L
_GLIBCXX_HAVE_ACOSL
_GLIBCXX_HAVE_ASINL
_GLIBCXX_HAVE_ATANL
_GLIBCXX_HAVE_LOCALE_H
_GLIBCXX_HAVE_ATTRIBUTE_VISIBILITY
__glibcxx_requires_valid_range
_GLIBCXX_HAVE___CXA_THREAD_ATEXIT_IMPL
__GCC_ATOMIC_TEST_AND_SET_TRUEVAL
__FLT_EVAL_METHOD__
_GLIBCXX_HAVE_TANL
_GLIBCXX_HAVE_FABSL
_GLIBCXX_HAVE_TANHL
_GLIBCXX_HAVE_STDALIGN_H
_GLIBCXX_HAVE_ISNANL
_GLIBCXX_HAVE_ECANCELED
_GLIBCXX_HAVE_ENOTRECOVERABLE
```

## Test 2

Using the same source file with line 16:
```cpp
value.  // line 16
//    ^---- column 7
```

```
$ rc --synchronous-completions -l test-case.cpp:16:7
 bar void bar() CXXMethod  myclass 
 foo void foo() CXXMethod  myclass 
 operator= myclass & operator=(const myclass &) CXXMethod  myclass 
 ~myclass void ~myclass() CXXDestructor  myclass 
 myclass myclass:: ClassDecl  myclass 
```

YCM on the same character
```
bar
myclass::
~myclass
operator=
```

## Test 3

Using the same source file with line 16:
```cpp
value.b  // line 16
//     ^---- column 8
```

```
$ rc --synchronous-completions -l test-case.cpp:16:8 | wc -l
1270
```

YCM on the same character
```
bar
```

# Comparison

## Test 1

As shown in the test, clang_codeCompleteAt returns many results (basically all candidates available at the location), however YCM does a filtering based on presence of all characters from query string (in this example `val`). Apart from that it does quite sophisticated candidate sorting:

https://github.com/Valloric/ycmd/blob/master/cpp/ycm/Result.cpp#L142

Thus results seen for Test 1 are nicely sorted.

## Test 2

The only difference here is that YCM does not offer `foo` method, because of the visibility of symbol.

## Test 3

This shows need of calling clang completion for a word boundary, in this case for location of `value`. instead of `value.b`. For received results YCM does same filtering as seen in Test 1 with query string equal to `b`.

To be honest, I really like rtags tool, mainly because of the existence of project object and I would be happy to enhance the tool to have as strong code completion as YCM has. Hope it's quite doable task. Are you interested in completion enhancement effort in this are in a way I described?

Thanks

**Comment by Andersbakken** [comment]
Hi

The fact that we didn't filter in rdm was based mostly on a
misunderstanding of how to use the completion API in clang and where to
ideally cache results.

I think you're completely right that we should filter in c++ rather than in
elisp. I've added some code for this but it's not nearly as fancy as YCM's
(basically only discarding the ones don't start with the prefix).

We're definitely always interested in contributions from the community and
if you wanted to write some code that improves this we would be very
thankful.

I'm not sure to what extent company-mode/auto-complete mode works well with
the YCM way of matching the completion or not. E.g.

obj->fbo matching object->frame_buffer_object() and that kind of thing but
we could always make it optional at the rdm side.

The relevant part of source right now would be CompletionThread.cpp at line
347:

                    if (node.completion.isEmpty() ||
(!request->prefix.isEmpty() && !text.startsWith(request->prefix))) {

Anders

**Comment by marxin** [comment]
Good!

I believe that having a similar set of sorting and filtering criteria could result in quite good results. We can also provide options that would enable/disable these heuristics.

I'm planning to do that as HackWeek project, which is a time slot when I'm allowed to work on personal open-source project. I expect that at the beginning of a new year.

I was bit inspired here with CamelHumps:
https://www.jetbrains.com/help/resharper/2016.2/Navigation_and_Search__CamelHumps.html
(btw. your sample 'obj->fbo' is a camel hump).

and idea of double completion is also quite interesting (showing for instance not visible symbols):
https://www.jetbrains.com/help/resharper/2016.1/Coding_Assistance__Code_Completion__Double.html
that 

and idea of double completion is also quite interesting (showing for instance not visible symbols):
https://www.jetbrains.com/help/resharper/2016.1/Coding_Assistance__Code_Completion__Double.html

**Comment by Andersbakken** [comment]
All of these ideas definitely sound interesting. Looking forward to see
what you come up with when you're free to take a look. Feel free to shoot
me any questions about how things currently work if anything's unclear.

Anders

**Comment by marxin** [comment]
Ok, my hackweek is over and I did quite some progress with the issue. However, it will still require some time to prepare a full-featured pull-request.

There's a description what was done:
1) When code completion is received, rtags find identifier prefix and shifts column to position after '.' or '->'
2) For results received by clang, more enhanced filtering and sorting is applied. Here I adopted approach used e.g. by Resharper or Monodevelop, where user can write starts of an identifier boundaries. For instance: MyNiceValueIdentifier can be matched by 'myvai'. It's all implemented in a separate file (string_playground.h).
3) Using https://github.com/nlohmann/json library, I serialize data in order to create a proper JSON result. Adding the library in a standard way should be done.

I have couple of questions:
a) Is it desired to provide such filtering and sorting by default? Do you like it?
b) May I remove the cumbersome --json serialization API which basically just wraps normal output to a JSON container?
c) I prepared various gtests, may I adopt them to 'make test' ?
d) Are you fine with usage of the JSON library?
e) Can we also change the XML API? It suffers from the very same problem.

There's link to my branch:
https://github.com/marxin/rtags/tree/smart-completion-and-refactoring

and corresponding changes in vim-rtags (if you are interested):
https://github.com/marxin/vim-rtags/tree/python-refactoring

Thanks for feedback, I'm ready to finish the task.

**Comment by Andersbakken** [comment]
Hi

So sorry about the delay. I've been a little swamped.

a) I think so. Filtering on the c++ side of things should speed things up.
b) You may indeed. It's all kinda hacked together.
c) Yes indeed.
d) Ideally I'd like to put this support into Rct
e) Same with this. Ideally it would go into Rct.

On a general level I'm fine with all of these changes and I'm looking
forward to the pull request when it's ready.

Anders

**Comment by marxin** [comment]
Hello.

I found some time to continue on that and I feel I'm quite close to do a submission. Still couple of new questions I have:

- https://github.com/Andersbakken/rtags/blob/master/src/RClient.cpp#L172 - the argument is unused in code completion; may I use the argument to identify an identifier prefix that we're searching for?
- are you aware about XML format consumers, maybe can be dropped eventually and replaces just with JSON
- I've notices tests and automated_tests folders in rtags repo, how can I run tests?
- Do you have a defined coding style, or do you use the emacs to do formatting?

**Comment by Andersbakken** [comment]
Hi

On Sun, May 28, 2017 at 2:35 PM, marxin <notifications@github.com> wrote:

> Hello.
>
> I found some time to continue on that and I feel I'm quite close to do a
> submission. Still couple of new questions I have:
>
>    - https://github.com/Andersbakken/rtags/blob/
>    master/src/RClient.cpp#L172 - the argument is unused in code
>    completion; may I use the argument to identify an identifier prefix that
>    we're searching for?
>
> It does seem to be used by the company backend though I'm not sure if does
what it's supposed to. I believe it's meant to do "server-side" filtering
of the results which I assume is what you want to use it for as well.

>
>    - are you aware about XML format consumers, maybe can be dropped
>    eventually and replaces just with JSON
>
> Not sure if anyone actually uses it. I guess I should check out of any of
the other known rtags editor frontends use it before killing it. I
certainly wouldn't mind killing it if no one uses it.


>    - I've notices tests and automated_tests folders in rtags repo, how
>    can I run tests?
>
> Apparently this has been broken for a while. Should work now.

You have to install nosetests and pyhamcrest

E.g.

pip install --user --upgrade nose
pip install --user --upgrade PyHamcrest

Then, from the root source directory run:

nosetests


>
>    - Do you have a defined coding style, or do you use the emacs to do
>    formatting?
>
> We sorta do but it's not really written down anywhere.

Someone else asked as well so I should maybe write it down.

I added a little section about our coding style in the readme. It might not
cover everything but it should have the basics.


regards
