### ISSUE TITLE
Allow wrapping of low-priority rp invocations

### ISSUE THREAD

**Issue by Nephyrin** [Andersbakken/rtags#599]
When both rdm and a normal compile are running side by side, rdm's reparsing competes with the real compile pretty heavily for resources, sometimes nearly doubling compile times. The built in option to run rp with niceness seems to do little -- 'nice' is well known to be fairly useless in linux-land.

This effect goes away entirely if I put rdm in a low-priority cgroup, but then the daemon itself becomes non-responsive during compiles for interactive usage.

It would be nice if there were a way to differentiate between low-priority rp invocations for indexing and interactive invocations to handle querying by the user. In the former case, an option to invoke a wrapper to spawn rp would make it easy to provide a `rp-but-in-my-lowprio-cgroup` wrapper for them, without affecting the parent process or interactive spawns of rp.

**Comment by Andersbakken** [comment]
rdm will by default look for an rp in the same directory. Would it work to just replace that with a shell script called rp that invokes the real rp from somewhere else? It's a little hacky I guess. Would it be good enough to have a configuration option for what executable rdm should run (defaulting to rp)? 

I honestly have no experience with cgroups. 

regards

Anders

**Comment by Nephyrin** [comment]
If rdm respected PATH it would make the solution less hacky, an --rp-path option would work too, if easier.

cgroups have a different interface depending on linux distro (systemd vs libcgroup vs just-go-touch-/sys/fs/cgroup) so integrating them directly would probably be a pain, but they let you do things like have groups of processes that only get idle CPU/Disk access so they have near zero impact on actual compiles or interactive apps.

The second part of this request would be some way of differentiating between rp invocations needed for user input (e.g. to reparse a file to provide a lookup) vs background invocations that are just catching up on dirty files. cgroups can be so effective that, if given literally-0 priority, the rp invocation won't finish until your compile is entirely done. If rp can be easily wrapped, this might be as simple as a dummy `rp --interactive` flag so the wrapper script can decide.

**Comment by Andersbakken** [comment]
I'll take a crack at adding something.

**Comment by Andersbakken** [comment]
I added some infrastructure that I believe will allow you to do this. You can now do the following:

rdm --rp-path=/path/to/rp-wrapper

Your wrapper will be passed args indicating the priority of the job. 

E.g.

--priority 6

Note that the majority of the data passed to rp is passed on stdin and is in binary form.

Priorities are currently defined thus:

Priority is essentially a bitfield at this point:

0x1: File is modified (dirty)
0x2: File has a active dependent, *
0x4: File is reindexed. E.g. someone called rc -V on the file. Normally
happens because rtags was used on an unsaved file.
0x8: File is active **

*) This basically means that the editor has a file open that the source
file in question depends on.

E.g. foo.cpp is being indexed and foo.h is currently open in the editor.

**) The file that is being indexed is currently open in the editor.

**Comment by Andersbakken** [comment]
Let me know if this suffices.

**Comment by Nephyrin** [comment]
You rock! This seems to work well. Here's the wrapper I'm using currently:

```bash
#!/bin/bash
set -e

mkdir -p /sys/fs/cgroup/{cpu,blkio}/rp
eval echo 20 \> /sys/fs/cgroup/cpu/rp/cpu.shares
eval echo 10 \> /sys/fs/cgroup/blkio/rp/blkio.weight
eval echo $$ \> /sys/fs/cgroup/cpu/rp/cgroup.procs
eval echo $$ \> /sys/fs/cgroup/blkio/rp/cgroup.procs

/usr/bin/rp "$@"
```

(I've given my user access to create cgroups, though on many systems the recommended way is to use a cgroup tool so as not to trip over systemd or similar)

I still need to add skipping the cgroup part for higher priorities, but generally this works perfectly -- rdm stays reponsive, rp invocations are in a low-priority cgroup and don't significantly compete with compiles for resources.

Thanks as usual for your excellent work on this.

**Comment by Andersbakken** [comment]
Awesome. I might try to use this myself.

Anders
