### ISSUE TITLE
cross compiling linux kernel

### ISSUE THREAD

**Issue by FreeBSD-Freak** [Andersbakken/rtags#626]
Hi, 
i do very much like rtags and emacs. I'm already using it for several projects (Linux/x86, bare metal armv7), but unfortunately I'm not able to get rtags indexing the linux kernel (cross compile Ubuntu 15.10 x86_64 -> armv7) properly. I did a softlink to gcc-rtags-wrapper.sh like described in documentation:

`which -a arm-linux-gnueabihf-gcc | xargs file`
`/usr/local/bin/arm-linux-gnueabihf-gcc: symbolic link to /user/local/bin/gcc-rtags-wrapper.sh`
`/usr/bin/arm-linux-gnueabihf-gcc:       symbolic link to arm-linux-gnueabihf-gcc-5 `

Observing rdm output i see many "Failed to parse clang [...]" passages like the following:
`Failed to parse clang -Wp,-MD,/home/user/devel/bitbucket/linux_module/.linux_module.o.d -nostdinc -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-dwarf2-cfi-asm -fno-ipa-sra -mabi=aapcs-linux -mno-thumb-interwork -mfpu=vfp -funwind-tables -mthumb -Wa,-mimplicit-it=always -Wa,-mno-warn-deprecated -march=armv7-a -msoft-float -Uarm -fno-delete-null-pointer-checks -O2 --param=allow-store-data-races=0 -Wframe-larger-than=1024 -fstack-protector -Wno-unused-but-set-variable -pg -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -std=gnu99 -Wall -Wstrict-prototypes -Wno-declaration-after-statement -fno-optimize-sibling-calls -c -ferror-limit=0 -Wall -fspell-checking -Wno-unknown-warning-option -DCC_HAVE_ASM_GOTO -DKBUILD_BASENAME=KBUILD_STR(linux_module) -DKBUILD_MODNAME=KBUILD_STR(linux_module) -DKBUILD_STR(s)=#s -DMODULE -D__KERNEL__ -D__LINUX_ARM_ARCH__=7 -isystem /usr/lib/gcc-cross/arm-linux-gnueabihf/5/include -I/home/user/devel/linux/bb-kernel/KERNEL/./arch/arm/include -I/home/user/devel/linux/bb-kernel/KERNEL/arch/arm/include/generated/uapi -I/home/user/devel/linux/bb-kernel/KERNEL/arch/arm/include/generated -I/home/user/devel/linux/bb-kernel/KERNEL/include -I/home/user/devel/linux/bb-kernel/KERNEL/./arch/arm/include/uapi -I/home/user/devel/linux/bb-kernel/KERNEL/arch/arm/include/generated/uapi -I/home/user/devel/linux/bb-kernel/KERNEL/./include/uapi -I/home/user/devel/linux/bb-kernel/KERNEL/include/generated/uapi -include /home/user/devel/linux/bb-kernel/KERNEL/./include/linux/kconfig.h -isystem /usr/lib/llvm-3.6/lib/clang/3.6.2/include/  /home/user/devel/bitbucket/linux_module/linux_module.c`

If i try to query some information about the c-file, rdm produces for example something like
`Failed to open /home/user/.rtags/_home_user_devel_bitbucket_linux__module_/4464/symbols /home/user/devel/bitbucket/linux_module/linux_module.c (2) 86`

Any ideas?

**Comment by Andersbakken** [comment]
The failed to parse message indicates that clang_parseTranslationUnit
failed. Normally there would be some error message printed before this. Can
you check if something references the same file in the output?

Also, you could try to run the whole command line and see if what kind of
errors you get. E.g.

# clang -Wp,-MD,/home/user/devel/bitbucket/linux_module/.linux_module.o.d
-nostdinc -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs
-fno-strict-aliasing -fno-common -Werror-implicit-function-declaration
-Wno-format-security -std=gnu89 -fno-dwarf2-cfi-asm -fno-ipa-sra
-mabi=aapcs-linux -mno-thumb-interwork -mfpu=vfp -funwind-tables -mthumb
-Wa,-mimplicit-it=always -Wa,-mno-warn-deprecated -march=armv7-a
-msoft-float -Uarm -fno-delete-null-pointer-checks -O2
--param=allow-store-data-races=0 -Wframe-larger-than=1024 -fstack-protector
-Wno-unused-but-set-variable -pg -Wdeclaration-after-statement
-Wno-pointer-sign -fno-strict-overflow -fconserve-stack
-Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -std=gnu99
-Wall -Wstrict-prototypes -Wno-declaration-after-statement
-fno-optimize-sibling-calls -c -ferror-limit=0 -Wall -fspell-checking
-Wno-unknown-warning-option -DCC_HAVE_ASM_GOTO
-DKBUILD_BASENAME=KBUILD_STR(linux_module)
-DKBUILD_M ODNAME=KBUILD_STR(linux_module) -DKBUILD_STR(s)=#s -DMODULE
-D__KERNEL__ -D__LINUX_ARM_ARCH__=7 -isystem
/usr/lib/gcc-cross/arm-linux-gnueabihf/5/include
-I/home/user/devel/linux/bb-kernel/KERNEL/./arch/arm/include
-I/home/user/devel/linux/bb-kernel/KERNEL/arch/arm/include/generated/uapi
-I/home/user/devel/linux/bb-kernel/KERNEL/arch/arm/include/generated
-I/home/user/devel/linux/bb-kernel/KERNEL/include
-I/home/user/devel/linux/bb-kernel/KERNEL/./arch/arm/include/uapi
-I/home/user/devel/linux/bb-kernel/KERNEL/arch/arm/include/generated/uapi
-I/home/user/devel/linux/bb-kernel/KERNEL/./include/uapi
-I/home/user/devel/linux/bb-kernel/KERNEL/include/generated/uapi -include
/home/user/devel/linux/bb-kernel/KERNEL/./include/linux/kconfig.h -isystem
/usr/lib/llvm-3.6/lib/clang/3.6.2/include/ /home/user/devel/bitbucket/
linux_module/linux_module.c

Anders

**Comment by FreeBSD-Freak** [comment]
It seems to be not a clang matter, because the error message says:
`bash: syntax error near unexpected token '('`
If i remove 
`-DKBUILD_BASENAME=KBUILD_STR(linux_module)
-DKBUILD_M ODNAME=KBUILD_STR(linux_module) -DKBUILD_STR(s)=#s`
 there is no bash error anymory. But i do not have a clue how to workaround this.

**Comment by Andersbakken** [comment]
Hi

Sorry about the delay. The issue is that the args need to be quoted.

E.g.

"clang" "-Wp,-MD,/home/user/devel/bitbucket/linux_module/.linux_module.o.d"
"-nostdinc" "-mlittle-endian" "-Wall" "-Wundef" "-Wstrict-prototypes"
"-Wno-trigraphs" "-fno-strict-aliasing" "-fno-common"
"-Werror-implicit-function-declaration" "-Wno-format-security" "-std=gnu89"
"-fno-dwarf2-cfi-asm" "-fno-ipa-sra" "-mabi=aapcs-linux"
"-mno-thumb-interwork" "-mfpu=vfp" "-funwind-tables" "-mthumb"
"-Wa,-mimplicit-it=always" "-Wa,-mno-warn-deprecated" "-march=armv7-a"
"-msoft-float" "-Uarm" "-fno-delete-null-pointer-checks" "-O2"
"--param=allow-store-data-races=0" "-Wframe-larger-than=1024"
"-fstack-protector" "-Wno-unused-but-set-variable" "-pg"
"-Wdeclaration-after-statement" "-Wno-pointer-sign" "-fno-strict-overflow"
"-fconserve-stack" "-Werror=implicit-int" "-Werror=strict-prototypes"
"-Werror=date-time" "-std=gnu99" "-Wall" "-Wstrict-prototypes"
"-Wno-declaration-after-statement" "-fno-optimize-sibling-calls" "-c"
"-ferror-limit=0" "-Wall" "-fspell-checking" "-Wno-unknown-warning-option"
"-DCC_HAVE_ASM_GOTO" "-DKBUILD_BASENAME=KBUILD_STR(linux_module)"
"-DKBUILD_M" "ODNAME=KBUILD_STR(linux_module)" "-DKBUILD_STR(s)=#s"
"-DMODULE" "-D__KERNEL__" "-D__LINUX_ARM_ARCH__=7" "-isystem"
"/usr/lib/gcc-cross/arm-linux-gnueabihf/5/include"
"-I/home/user/devel/linux/bb-kernel/KERNEL/./arch/arm/include"
"-I/home/user/devel/linux/bb-kernel/KERNEL/arch/arm/include/generated/uapi"
"-I/home/user/devel/linux/bb-kernel/KERNEL/arch/arm/include/generated"
"-I/home/user/devel/linux/bb-kernel/KERNEL/include"
"-I/home/user/devel/linux/bb-kernel/KERNEL/./arch/arm/include/uapi"
"-I/home/user/devel/linux/bb-kernel/KERNEL/arch/arm/include/generated/uapi"
"-I/home/user/devel/linux/bb-kernel/KERNEL/./include/uapi"
"-I/home/user/devel/linux/bb-kernel/KERNEL/include/generated/uapi"
"-include"
"/home/user/devel/linux/bb-kernel/KERNEL/./include/linux/kconfig.h"
"-isystem" "/usr/lib/llvm-3.6/lib/clang/3.6.2/include/"
"/home/user/devel/bitbucket/linux_module/linux_module.c"

This actually happens in rtags but it gets lost when we print the args.

Anders

**Comment by FreeBSD-Freak** [comment]
For building a kernel-module I'm using the build-infrastructure of the kernel. Unfortunately I'm not aware how to manage the compiler calls in such a way that all of the arguments are covered with quotes.

**Comment by cslux** [comment]
@FreeBSD-Freak I'm not 100% sure if it will help you, but I have used [Bear](https://github.com/rizsotto/Bear) to get a compile_commands.json for the kernel compile commands for an ARM platform.  Than I have passed the compile_commands.json file to rtags, this worked pretty well.

Christian

**Comment by cslux** [comment]
However, you may need to replace the `cc` in the compile_commands.json file, `Bear` creates, if you are using the `rdm` flag `--enable-compiler-manager`.

**Comment by Andersbakken** [comment]
I think Christian is right that using bear might be the best way to
generate compile_commands.json file.

I think the args likely are quoted correctly the way pass them to rtags
(using rtags-gcc-wrapper.sh).
What I meant was that to be able to run a similar command using clang you'd
need to use this command rather than the one I gave you first:

"clang" "-Wp,-MD,/home/user/devel/bitbucket/linux_module/.linux_module.o.d"
"-nostdinc" "-mlittle-endian" "-Wall" "-Wundef" "-Wstrict-prototypes"
"-Wno-trigraphs" "-fno-strict-aliasing" "-fno-common"
"-Werror-implicit-function-declaration" "-Wno-format-security" "-std=gnu89"
"-fno-dwarf2-cfi-asm" "-fno-ipa-sra" "-mabi=aapcs-linux"
"-mno-thumb-interwork" "-mfpu=vfp" "-funwind-tables" "-mthumb"
"-Wa,-mimplicit-it=always" "-Wa,-mno-warn-deprecated" "-march=armv7-a"
"-msoft-float" "-Uarm" "-fno-delete-null-pointer-checks" "-O2"
"--param=allow-store-data-races=0" "-Wframe-larger-than=1024"
"-fstack-protector" "-Wno-unused-but-set-variable" "-pg"
"-Wdeclaration-after-statement" "-Wno-pointer-sign" "-fno-strict-overflow"
"-fconserve-stack" "-Werror=implicit-int" "-Werror=strict-prototypes"
"-Werror=date-time" "-std=gnu99" "-Wall" "-Wstrict-prototypes"
"-Wno-declaration-after-statement" "-fno-optimize-sibling-calls" "-c"
"-ferror-limit=0" "-Wall" "-fspell-checking" "-Wno-unknown-warning-option"
"-DCC_HAVE_ASM_GOTO" "-DKBUILD_BASENAME=KBUILD_STR(linux_module)"
"-DKBUILD_M" "ODNAME=KBUILD_STR(linux_module)" "-DKBUILD_STR(s)=#s"
"-DMODULE" "-D__KERNEL__" "-D__LINUX_ARM_ARCH__=7" "-isystem"
"/usr/lib/gcc-cross/arm-linux-gnueabihf/5/include"
"-I/home/user/devel/linux/bb-kernel/KERNEL/./arch/arm/include"
"-I/home/user/devel/linux/bb-kernel/KERNEL/arch/arm/include/generated/uapi"
"-I/home/user/devel/linux/bb-kernel/KERNEL/arch/arm/include/generated"
"-I/home/user/devel/linux/bb-kernel/KERNEL/include"
"-I/home/user/devel/linux/bb-kernel/KERNEL/./arch/arm/include/uapi"
"-I/home/user/devel/linux/bb-kernel/KERNEL/arch/arm/include/generated/uapi"
"-I/home/user/devel/linux/bb-kernel/KERNEL/./include/uapi"
"-I/home/user/devel/linux/bb-kernel/KERNEL/include/generated/uapi"
"-include"
"/home/user/devel/linux/bb-kernel/KERNEL/./include/linux/kconfig.h"
"-isystem" "/usr/lib/llvm-3.6/lib/clang/3.6.2/include/"
"/home/user/devel/bitbucket/linux_module/linux_module.c"

Can you run that and send the output back?

Anders

**Comment by FreeBSD-Freak** [comment]
If i execute this line, the output is like this:
clang: error: unknown argument: '-fno-common-Werror-implicit-function-declaration'
clang: error: unknown argument: '-fno-ipa-sra'
clang: error: unknown argument: '-mthumb-Wa,-mimplicit-it=always'
clang: error: unknown argument: '-pg-Wdeclaration-after-statement'
clang: error: unknown argument: '-fno-strict-overflow-fconserve-stack'
clang: error: unknown argument: '-c-ferror-limit=0'
clang: error: no such file or directory: 'ODNAME=KBUILD_STR(linux_moduel)'
clang: error: unsupported argument '-mno-warn-deprecated' to option 'Wa,'
clang: warning: optimization flag '-fno-delete-null-pointer-checks' is not supported

@cslux
I will have a look at Bear, thanks for the tip.

**Comment by cslux** [comment]
Those errors indicate that the compile commands, I assume GCC ones, contain GCC
specific flags, which clang doesn't support or use different names for them.

You have several possibilities to get rid of those errors, but isn't required:

1. Suppress them via the `rdm` flag `--block-argument`
2. Transform them via the `rdm` flag `--arg-transform`
3. Pipe the compile commands through `sed` and transform them.
4. ...

Christian

**Comment by Andersbakken** [comment]
Yeah. We do kinda maintain a blacklist inside of Source.cpp too though so
maybe we could just add all of these. I think it's relatively likely that
this is the issue.

Anders

**Comment by FreeBSD-Freak** [comment]
Hi,
i didn't get gcc-rtags-wrapper.sh to work with the kernel. Using Bear to get a compile_commands.json worked out of the box, thank you for the tip.

**Comment by Andersbakken** [comment]
Glad to hear. I might try to look into that. Maybe things need to be quoted
some more.

Anders
