### ISSUE TITLE
too slow with big compile_commands.json

### ISSUE THREAD

**Issue by vardanian** [Andersbakken/rtags#631]
I've compile_commands.json which is 15Mb in size.
After waiting for about 15 min rdm handled less than 5%.

**Comment by cslux** [comment]
@vardanian Do you mean rdm has read or compiled less than 5%.

**Comment by Andersbakken** [comment]
We try to be as fast as we possibly can but almost certainly about 90% of
the time is spent inside of clang and there's nothing we can do about it.

Basically whenever you see a line of output from rdm like these:

[ 67%] 267/397 16:38:02 <filename> in 865ms. (521 syms, 644 symNames, 2
includes, 1 of 246 files, symbols: 661 of 10968, 11858 cursors)
(802/49/7ms) (dirty). (priority 1)

Thjis implies that 802 ms were spent inside clang_parseTranslationUnit, 49
ms were spent visiting the AST and 7ms were spent writing the data to the
database.

Short of getting better support for PCH which would speed things up there's
very little we can do to substantially speed it up. Did you build your own
clang? If so, it's imperative that you specify --enable-optimizations or
something to that effect when you configure.

Anders

**Comment by vardanian** [comment]
@cslux I mean read.
This is very sad. In fact this means that rtags can't be used for big projects((

**Comment by cslux** [comment]
@vardanian I use rtags for Chromium with a compile_commands.json size of ~40 MB in size, containing ~12000 translation units, if I include everything it's ~80 MB containing ~25000 translation units, I can't really complain about the speed, memory usage etc. Eclipse for instance is unable to handle it all together, even though I gave the VM more than 8 GB RAM. In contrast `rdm` memory usage is always roughly around 200-800 MB, plus 200-400 MB for Emacs with more than 300 buffers open, that's far less what Eclipse would need, when it wouldn't constantly crash due to the size of Chromium. However, you could also try [irony](https://github.com/Sarcasm/irony-mode) or [ycmd](https://github.com/Valloric/ycmd), they are also using clang for parsing. I haven't tried [ycmd](https://github.com/Valloric/ycmd) but I wasn't happy with [irony](https://github.com/Sarcasm/irony-mode)

Some details:  
``` bash
ls -gGh
-rw-r--r--.   1  78M Mar 12 18:26 compile_commands.json

time rc -J compile_commands.json
[Server] Compilation database loaded

real    1m39.382s
user    0m0.003s
sys     0m0.004s
```

regards,
Christian

**Comment by Andersbakken** [comment]
Just to be sure I understand. You're saying that rdm has gotten to about 5%
after 15 minutes indicated like this?

[ 15%] ... file.cpp ...

How long does it take to compile the project? rtags usually takes roughly
the same amount of time as compiling the project.

I did the following.

cd ~/dev/rtags
make clean
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=1
time make -j8

And I got:

real 0m26.365s
user 2m43.879s
sys 0m8.947s

Then, when I do:

rc -J .

I get

Jobs took 30.24s, (avg 0.51s). We're using 245mb of memory.

Can you try the same test with indexing rtags itself?

If rtags is a lot slower than the compile something seems to be fishy.

Anders

**Comment by vardanian** [comment]
@cslux @Andersbakken 
thanks guys for your operative answers! I'll try today to build/index rates itself, and write back.

**Comment by vardanian** [comment]
> CXX=/opt/gcc-5.2.0/bin/g++ CC=/opt/gcc-5.2.0/bin/gcc cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=1 .
...

> time make
....

real	3m44.050s
user	3m28.376s
sys	0m12.064s


> LD_LIBRARY_PATH=/opt/gcc-5.2.0/lib64 rdm & 2>dm.log
> Running with 2 jobs, using args: -ferror-limit=0 -Wall -fspell-checking -Wno-unknown-warning-option
Includepaths:
FileSystemWatcher::watch() '/home/vram.vardanian/rtags/build/' doesn't seem to be watchable
Output from /home/vram.vardanian/rtags/src/QueryMessage.cpp:
Wrong protocol 83 vs 84
ClangIndexer error

Output from /home/vram.vardanian/rtags/src/SymbolInfoJob.cpp:
Wrong protocol 83 vs 84
ClangIndexer error

Output from /home/vram.vardanian/rtags/src/ListSymbolsJob.cpp:
Wrong protocol 83 vs 84
ClangIndexer error

Output from /home/vram.vardanian/rtags/src/RTags.cpp:
Wrong protocol 83 vs 84
ClangIndexer error

Output from /home/vram.vardanian/rtags/src/rdm.cpp:
Wrong protocol 83 vs 84
ClangIndexer error
...
...

[ 98%] 60/61 19:03:26 ~/rtags/src/CompilerManager.cpp indexing crashed.
Output from /home/vram.vardanian/rtags/src/rct/rct/SocketClient.cpp:
Wrong protocol 83 vs 84
ClangIndexer error

[100%] 61/61 19:03:26 ~/rtags/src/rct/rct/SocketClient.cpp indexing crashed.
Jobs took 2.31s, (avg 0.04s). We're using 4mb of memory.

**Comment by cslux** [comment]
@vardanian The error **Wrong protocol NUM vs NUM** indicates that you are running mixed versions of `rc` and `rdm`. Please check if you have installed multiple times RTags, by issuing the following command `which -a rdm`.
``` bash
which -a rdm
# Output is in my case
/usr/bin/rdm
/bin/rdm
```
If you have multiple version installed remove all of them, and install RTags again, otherwise restart `rdm`, as this can also happen, if you have compiled, and installed RTags, while `rdm` was running. 

Christian

**Comment by vardanian** [comment]
@cslux @Andersbakken 
after specifying LIBCLANG_LLVM_CONFIG_EXECUTABLE i successfully indexed rtags!

However, though I've got it working, the issue with speed remains.
I run `rc -J .` and after 10min ram indexed 7%. I mean I see 

```
[  5%] 166/3405 17:30:13 ~/repos/tb/src/servers/connectivity/bats/md_pitch_mcast/src/Instrument.cpp in 7183ms. (9378 syms, 18535 symNames, 161 includes, 27 of 1314 files, symbols: 22894 of 67896, 84430 cursors, 26 queried 1ms) (6661/445/54ms) (reindex). (header-error)
Output from /home/vram.vardanian/repos/tb/src/servers/connectivity/bats/md_pitch_mcast/src/Instrument.cpp:
/opt/gcc-5.2.0/lib/gcc/x86_64-unknown-linux/5.2.0/../../../../include/c++/5.2.0/type_traits:1385:8: error: expected ';' after struct
/opt/gcc-5.2.0/lib/gcc/x86_64-unknown-linux/5.2.0/../../../../include/c++/5.2.0/type_traits:1385:9: error: expected unqualified-id
/opt/gcc-5.2.0/lib/gcc/x86_64-unknown-linux/5.2.0/../../../../include/c++/5.2.0/type_traits:1391:8: error: expected ';' after struct
/opt/gcc-5.2.0/lib/gcc/x86_64-unknown-linux/5.2.0/../../../../include/c++/5.2.0/type_traits:1391:9: error: expected unqualified-id
/opt/gcc-5.2.0/lib/gcc/x86_64-unknown-linux/5.2.0/../../../../include/c++/5.2.0/type_traits:1397:8: error: expected ';' after struct
/opt/gcc-5.2.0/lib/gcc/x86_64-unknown-linux/5.2.0/../../../../include/c++/5.2.0/type_traits:1397:9: error: expected unqualified-id
/opt/gcc-5.2.0/lib/gcc/x86_64-unknown-linux/5.2.0/../../../../include/c++/5.2.0/bits/exception_ptr.h:191:51: error: expected ';' at end of declaration
/opt/gcc-5.2.0/lib/gcc/x86_64-unknown-linux/5.2.0/../../../../include/c++/5.2.0/bits/exception_ptr.h:191:52: error: expected unqualified-id
/opt/gcc-5.2.0/lib/gcc/x86_64-unknown-linux/5.2.0/../../../../include/c++/5.2.0/backward/binders.h:130:6: error: expected ';' after class
/opt/gcc-5.2.0/lib/gcc/x86_64-unknown-linux/5.2.0/../../../../include/c++/5.2.0/backward/binders.h:130:7: error: expected unqualified-id
/opt/gcc-5.2.0/lib/gcc/x86_64-unknown-linux/5.2.0/../../../../include/c++/5.2.0/backward/binders.h:165:6: error: expected ';' after class
/opt/gcc-5.2.0/lib/gcc/x86_64-unknown-linux/5.2.0/../../../../include/c++/5.2.0/backward/binders.h:165:7: error: expected unqualified-id
/home/vram.vardanian/repos/tb/build.x86_64-unknown-linux/include64/ace-5.7/ace/OS_NS_unistd.inl:766:14: warning: explicitly assigning value of variable of type 'ACE_OVERLAPPED *' to itself [-Wself-assign]
/home/vram.vardanian/repos/tb/build.x86_64-unknown-linux/include64/ace-5.7/ace/OS_NS_unistd.inl:1219:14: warning: explicitly assigning value of variable of type 'ACE_OVERLAPPED *' to itself [-Wself-assign]
/opt/gcc-5.2.0/lib/gcc/x86_64-unknown-linux/5.2.0/../../../../include/c++/5.2.0/backward/auto_ptr.h:54:6: error: expected ';' after struct
/opt/gcc-5.2.0/lib/gcc/x86_64-unknown-linux/5.2.0/../../../../include/c++/5.2.0/backward/auto_ptr.h:54:7: error: expected unqualified-id
/opt/gcc-5.2.0/lib/gcc/x86_64-unknown-linux/5.2.0/../../../../include/c++/5.2.0/backward/auto_ptr.h:281:6: error: expected ';' after class
/opt/gcc-5.2.0/lib/gcc/x86_64-unknown-linux/5.2.0/../../../../include/c++/5.2.0/backward/auto_ptr.h:281:7: error: expected unqualified-id
/opt/gcc-5.2.0/lib/gcc/x86_64-unknown-linux/5.2.0/../../../../include/c++/5.2.0/backward/auto_ptr.h:290:6: error: expected ';' after class
/opt/gcc-5.2.0/lib/gcc/x86_64-unknown-linux/5.2.0/../../../../include/c++/5.2.0/backward/auto_ptr.h:290:7: error: expected unqualified-id
/home/vram.vardanian/repos/tb/src/libraries/types/headers/types/MMTFlags.h:125:35: warning: array subscript is of type 'char' [-Wchar-subscripts]
/home/vram.vardanian/repos/tb/src/servers/connectivity/bats/md_pitch_mcast/src/Instrument.h:70:29: warning: private field 'm_app' is not used [-Wunused-private-field]


```
 
So can you please tell me,
1. does rdm persists somewhere index database? I mean do I need to run rc -J every time rdm stopped/started?
2. Why I'm getting errors above?

**Comment by vardanian** [comment]
`/opt/gcc-5.2.0/lib/gcc/x86_64-unknown-linux/5.2.0/../../../../include/c++/5.2.0/type_traits:1385:8: error: expected ';' after struct`

I use clang for building, also specified `LIBCLANG_LLVM_CONFIG_EXECUTABLE=/opt/llvm-3.7.0/bin/llvm-config` and still I see `/opt/gcc-5.2.0/lib/gcc/`. Why?

**Comment by Andersbakken** [comment]
Clang generally relies on gcc system headers on linux. If I run clang like
this:

$ clang -v

I get:

Ubuntu clang version 3.6.2-3ubuntu1 (tags/RELEASE_362/final) (based on LLVM
3.6.2)
Target: x86_64-pc-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/5.2.1
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.2.1
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.2.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.2.1
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.2.1
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64

The errors might definitely be problematic.

Could you try to index RTags itself instead of the kernel? Like I mentioned
earlier. It should index it in a comparable amount of time as making it
takes.

Anders

**Comment by vardanian** [comment]
@Andersbakken 
I already indexed rtags. I didn't index kernel.
And, yes, indexing takes comparable amount of time.

**Comment by vardanian** [comment]
@Andersbakken 
Our project take >1h to compile on my machine, we use distcc and ccache to speed things up(~25m).
~1h hour for indexing is acceptable, if I have to index it once.
So the question is - does rdm persists index database? I mean do I need to run rc -J and wait every time rdm stopped/started?

**Comment by cslux** [comment]
Yes, the database is persistent! Rdm will schedule reindexing when
required, unless you have disabled it (see `rdm --help`).

The default location of the database is ~/.rtags

Christian

**Comment by cslux** [comment]
It's worth to mention that rdm also tracks changes made to the compile_commands.json file and will reload it when required. 

In short after your first indexing only those files which have been changed, will be reindexed, like eclipse does it by default, plus, if you have used the -J option of rdm, it will also reload that file if it has changed, which doesn't mean everything gets reindexed, if rdm reloads the compile_commands.json file. 

Hope that information helps you! 

Christian

**Comment by vardanian** [comment]
many thanks!
I think in this case slow indexing is not such a big issue.

**Comment by vardanian** [comment]
@cslux @Andersbakken  
One more question please.
I've indexed some project (via `rc -J .`), and after some time I changed branch which resulted in some code changes. Then I did rebuild, and got some new compile_commands.json.
So, in this case, do I need to rerun `rc -J .` ? Or all changes (modified/added/deleted files) are tracked by rdm automatically?

**Comment by cslux** [comment]
Everything will and should be tracked by rdm!

Christian

**Comment by vardanian** [comment]
@cslux thanks!

**Comment by cslux** [comment]
@vardanian My pleasure!
