### ISSUE TITLE
clarify the column value for rc --code-completion-at/--prepare-code-completion-at

### ISSUE THREAD

**Issue by ville-h** [Andersbakken/rtags#634]
`rc --synchronous-completions --code-complete-at /home/user/projects/src/file:4:K`

In above I am not sure what the column value K should be to get the narrowest set of completion suggestions? For member function access it seems to be that it should be the location of '.'? What about non-member functions? How do i limit the output to any prefix the user has already entered?

Also what's the purpose of --prepare-code-completion-at?

**Comment by Andersbakken** [comment]
The limiting of the completions actually doesn't happen inside rc actually. This is mostly due to our elisp doing it that way and we could add something. 

E.g.

functions without ->, . or :: you should specify the location of the first character in your string.

E.g.

1: void foo()
2: {
3:     startingToCompl 
4: }

You should pass src.cpp:3:4

src.cpp:3.1 would give the  same results.

It's then the job of the caller to filter out results based on the current prefix. The reason it is structured like this is that you would get the same results if you erased the whole string you had there and as such it seems like the appropriate place to cache the results. We could add a switch to filter out results based on a prefix.

Hope this helps.

Anders

**Comment by Andersbakken** [comment]
Oh. And --prepare-code-completions basically makes rdm create the completion results for the location in question and cache them. A subsequent call to --code-complete-at (assuming the former is finished) should be more or less instant.

**Comment by ville-h** [comment]
also is it possible to get the output from --code-complete-at with out any xml stuff? just one completion per line.

**Comment by Andersbakken** [comment]
Sure thing. It should ditch the xml by default now.

**Comment by ville-h** [comment]
that was rather quick. thanks!

**Comment by Andersbakken** [comment]
My pleasure.
Anders
