### ISSUE TITLE
Broken C++11 detection?

### ISSUE THREAD

**Issue by Wasabichicken** [Andersbakken/rtags#648]
Hi,

> rtags$ cmake .
> ...
> CMake Error at src/rct/rct.cmake:239 (message):
>   C++11 support not detected.  rct requires a modern compiler, GCC >= 4.8 or Clang >= 3.2 should suffice
> Call Stack (most recent call first):
>   src/CMakeLists.txt:44 (include)
> 
> -- Configuring incomplete, errors occurred!

My GCC is old (4.6.3, this is Ubuntu 12.04), but Clang is 3.4. CMake is version 2.8.7.

> $ llvm-config --version
> 3.4
> $ cmake --version
> cmake version 2.8.7

Workaround suggestions are very welcome. :-|

**Comment by Andersbakken** [comment]
I believe you should be able to build it like this then:

CC=clang CXX=clang++ cmake /path/to/rtags

Anders

**Comment by toojays** [comment]
You may find that you still can't build, because your clang depends on GCC's libstdc++, which may not be new enough. If you run `clang -v` you'll see which GCC libraries Clang will use.

You can get newer GCC for Ubuntu 12.04 here:
https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test?field.series_filter=precise

Clang 3.4 may choke on some of the newer GCC headers. If that happens you can follow instructions at http://llvm.org/apt/ to get a more recent Clang for your system.

**Comment by okovko** [comment]
I am getting this same problem. I made a new ticket about it with the details. Please and thanks for any attention :)
