### ISSUE TITLE
Do we need BerkeleyDb or Sqlite to store the database?

### ISSUE THREAD

**Issue by ngkaho1234** [Andersbakken/rtags#700]
I realize that looking up a symbol in large projects like Linux kernel is quite slow when harddrive is used to store the database.

**Comment by Andersbakken** [comment]
The database is too big to be stored in memory and I think our
implementation is relatively efficient as long as disk access isn't
prohibitively bad. We used to use leveldb and found that to be too slow.
After that we went to an in-memory datastructure but got into problems on
larger projects. Now we have our own homegrown database that I believe
performs relatively well. At least a fair bit better than leveldb which I
think is mostly due to it being written for the exact dataset we have.
Also, we wouldn't have any need for actual SQL so I doubt berkeleydb or
sqlite would be a good fit.

The main performance problems we had with leveldb had to do with updating,
not lookups. The model we have now makes this process more streamlined.

Anders
