### ISSUE TITLE
Buffer coding system changes

### ISSUE THREAD

**Issue by chep** [Andersbakken/rtags#702]
Hi Anders,

I have a strange bug that I cannot reproduce easily.

I open a file encoded with utf-8 and containing accentuated characters, like
this:

/* Ceci est un commentaire en français avec des caractères accentués et des truc bizarres */
int main()
{
	return 0;
}

When rtags is activated, sometimes, when I save the file, buffer coding system
information disappear in the mode line (it used to display 'U') and all my
accentuated characters are replaced by their code (\233 for example).

The easiest way I found to "fix" this is to close the file and reopen it.

It only happens when I save the file and when there is no syntax error. I tried
to debug it but could not find any entry point. I found 'rtags-after-save-hook'
but 'rtags-reindex-on-save' is nil for me so it should do nothing.

Can you tell me what is executed when I save a file? I think this is because of
code check, when errors and warning are highlighted because it only happen when
the code is syntactically correct.

Thanks

**Comment by Andersbakken** [comment]
My suspicion is that this has to do with rtags-goto-line-col which
temporarily changes the (set-buffer-multibyte).

I refactored it a little because I think it would restore the previous
setting if the line col are outside of the buffers bounds. Hopefully it
won't happen anymore.

To repro I think you could just do this:

A) open file
B) make a small change
C) M-: (rtags-goto-line-col 1000000 1000000)

I think this should reproduce the problem before the fix that I just
pushed. Can you verify?

regards
Anders

**Comment by chep** [comment]
Hi Anders,
Problem reproduced with rtags-goto-line-col. And fixed after a git pull.
Thank you

**Comment by Andersbakken** [comment]
Thanks. Glad to hear.

Anders
