### ISSUE TITLE
Problem w/ automatic company popup

### ISSUE THREAD

**Issue by jbeigel** [Andersbakken/rtags#727]
I have a problem with company in Spacemacs in conjunction with rtags. I'll report this here, because everything works as intended when I don't use rtags.

Normally, auto-completion via company is triggered automatically (after minimum delay and with minimum prefix), but this does not happen when using company-rtags. The strange thing is, when I issue company-complete explicitly, the completions are displayed correctly and immediately, so it's probably not a problem of rdm.

Does anyone have an idea how to debug this?

**Comment by Andersbakken** [comment]
Hm. TBH I don't actually use completions daily. I think the reason it
doesn't happen is that generating the clang completions is rather costly on
CPU so we don't automatically do it unless told to. I think you might be
able to better diagnose it by running rdm with --completion-logs and
checking the output to see what is going on.

Also, make sure you're rtags-completions-timer-interval is set to something
reasonable. What it means basically is that after moving the cursor and
waiting this amount of seconds we will schedule a preemptive
completion-request to get the cache primed.

Anders

**Comment by jbeigel** [comment]
rtags-completions-timer-interval is set to 1. But I think the problem is not that the cache is not primed. I'm just wondering why the completion popup does not popup automatically, even when the correct results are available (when I trigger the popup manually it's shown immediately with the correct results).

I'm also quite sure that this used to work, but I'm not aware of any configuration changes that could prevent the popup from appearing automatically (as I said: when I remove rtags from my Emacs config, the company popup does appear automatically).

**Comment by bcclaywell** [comment]
I'm having the same problem with company-rtags. I'm a new user to rtags so I can't say if behavior has changed, but here's what I've witnessed:

---

1. Type e.g. 4 characters and wait for the popup -- nothing happens
1. After waiting a few seconds, type a 5th character -- popup appears
1. After that popup appears, erase the characters typed, then retype the same 4 characters that didn't cause a popup before -- popup appears this time

---

1. Type e.g. 4 characters and wait for the popup -- nothing happens
1. After waiting a few seconds, erase the characters typed and retype them -- popup appears
1. After waiting a longer period of time (on the order of minutes?), erase and retype the same 4 characters -- nothing happens

---

1. Set company-idle-delay to 0 -- popup appears instantly after 3rd character typed

---

Based on this behavior it does seem like the popup is waiting for a cache to be primed, and maybe an event should fire when the caching is complete in order to cause the popup to appear?

**Comment by Andersbakken** [comment]
I'll try to dig into what might be happening.

**Comment by jbeigel** [comment]
This seems to be solved by the latest changes/fixes to #719, so I'll close this issue. Thanks!

**Comment by bcclaywell** [comment]
The latest build looks to have solved my issues as well. Thanks!
