### ISSUE TITLE
how to navigate the stl?

### ISSUE THREAD

**Issue by introom** [Andersbakken/rtags#782]
Hi.

I've no specific project, but only want to navigate the stl.

My usage is like this:
Open a stl file, for example, v1/queue and then navigate between it. (jump to deifinition)

How to achieve that?

Thanks.

**Comment by Andersbakken** [comment]
It should be enough to create a single main.cpp file, include all the
relevant headers (<queue> etc) and index main.cpp

Note that due to some intrinsics of how clang works some template functions
might not get indexed unless actually invoked. In other words, I would
recommend actually invoking most/all of the member functions in std::queue

E.g.

#include <queue>

int main()
{
     std::queue<int> q;
     q.push_back(1);
     q.clear();
     // etc etc
     return 0;
}

regards

Anders
