### ISSUE TITLE
rtags-find-symbol-at-point breaks code checks&completion by following symlinks

### ISSUE THREAD

**Issue by stunpix** [Andersbakken/rtags#807]
**Background**
I'm using flycheck+irony for checks'n'completions and rtags for navigation. I have two projects sharing same modules by symlinking them. Here's dir tree:

```
modules\
    mod1\
        src\
    mod2\
        src\
prj1\
    mods -> ../modules
    compile_commands.json
prj2\
    mods -> ../modules
    compile_commands.json
```

Each project must be compiled with its own configuration and they are using compile_commands.json for code completion and checks. This works fine.

**Problem**
By doing `rtags-find-symbol-at-point` at any symbol defined under `prj1/mods` or `prj2/mods`, rtags follows symlinks and open files from `modules`. This breaks code completion and checks in opened file, since `modules` has no commands json file.

Who is following symlinks, rtags or emacs? How I can disable this for `rtags-find-symbol-at-point` and similar?

Tried to `(setq find-file-visit-truename nil)`, but it not helped.

**Comment by stunpix** [comment]
After debugging I found that it's `rc`. It unwraps symlinks to files with definitions. Still can't find how to tell `rc` to not follow symlinks.

**Comment by Andersbakken** [comment]
Hi Alexanders

As it is rtags always resolves files to their realpath(3).

I just added a mode to try to optionally avoid this however.

To use:

echo "--no-realpath" >> ~/.rcrc
echo "--no-realpath" >> ~/.rdmrc

Wipe the database. (rdm -C)

restart

I haven't tested it much so there may very well be bugs.

Anders

**Comment by stunpix** [comment]
Wow. That was fast. 👍 Thanks a lot, I'll check it.

Just curious, why real paths were selected as default? AFAIK many tools by default aren't unrolling symlinks to real paths unless user requires that.

**Comment by stunpix** [comment]
`--no-realpath` option is missing in `rdm.cpp`:

```diff
diff --git a/src/rdm.cpp b/src/rdm.cpp
index 7a52b0e..f285e62 100644
--- a/src/rdm.cpp
+++ b/src/rdm.cpp
@@ -332,6 +332,7 @@ int main(int argc, char** argv)
         { RpPath, "rp-path", 0, required_argument, String::format<256>("Path to rp (default %s).", defaultRP().constData()) },
         { LogTimestamp, "log-timestamp", 0, no_argument, "Add timestamp to logs." },
         { SandboxRoot, "sandbox-root",  0, required_argument, "Create index using relative paths by stripping dir (enables copying of tag index db files without need to reindex)." },
+        { NoRealPath, "no-realpath", 0, no_argument, "Don't use realpath(3) for files" },
         { Noop, "config", 'c', required_argument, "Use this file (instead of ~/.rdmrc)." },
         { Noop, "no-rc", 'N', no_argument, "Don't load any rc files." }
     };
```

**Comment by stunpix** [comment]
Anyway, even with patch from previous comment emacs still opens file at real location.

**Comment by Andersbakken** [comment]
Hi Alexander

Thanks. I forgot to add that switch to rdm.

Anyway. I have the following scenario working now:

$ cat .rdmrc
--no-realpath
$ cat .rcrc
--no-realpath

TESTDIR=$HOME/temp/807
rm -rf $TESTDIR
mkdir -p $TESTDIR/actualfiles
cd $TESTDIR
echo "enum { Foo };" > actualfiles/foo.h
echo -e "#include \"foo.h\"\nint main() { return Foo; }\n" >
actualfiles/main.cpp
echo -e "#include \"actualfiles/foo.h\"\nint foo() { return Foo; }\n" >
foo.cpp
ln -s actualfiles/* .
touch Makefile
rc -c c++ foo.cpp
rc -c c++ main.cpp
sleep 2
rc -f main.cpp:2:21
foo.h:1:8:      enum { Foo };
rc -f foo.cpp:2:21
actualfiles/foo.h:1:8:  enum { Foo };

main.cpp includes "foo.h" which is the symlink,
foo.cpp includes "actualfiles/foo.h" which is the real file.

The issue was that rp didn't know about --no-realpath and thus would
resolve the files.

Let me know if it works for you.

Anders

**Comment by stunpix** [comment]
Issue is fixed, I'm able to open files at their symlinked paths!

Thank you! 👍
