### ISSUE TITLE
Missing git tags for releases

### ISSUE THREAD

**Issue by marxin** [Andersbakken/rtags#845]
I've notived that the last git release tag is v2.3, while current version of the project is 2.5.104. I would like to bump version of openSUSE package, however I'm not sure which revisions can I consider as stable?

**Comment by Andersbakken** [comment]
Good question :-) We don't really have releases in the traditional sense. Let me add a tag for v2.5.

**Comment by Andersbakken** [comment]
Sorry about the delay. There's not really a stable branch for RTags :-)

I kinda bump the version every once in a while. We're a small team and we
don't have too much in the way of release engineering or autotests so
there's not that much to base the perception of stability on. In general. I
just upped it to v2.6 so that's probably a good one to use right now :-)

Anders
