### ISSUE TITLE
Feature request: Call graph 

### ISSUE THREAD

**Issue by martong** [Andersbakken/rtags#862]
We could display the tree of the callers of a specific function up to main(). It could work similarly to find references, but recursively.

**Comment by Andersbakken** [comment]
This is actually already there.

rtags-references-tree

I basically never use rtags-find-references-at-point, rtags-references-tree
is pretty much a drop-in replacement.

Anders

**Comment by martong** [comment]
That is surely okay for emacs. However in vim (https://github.com/lyuts/vim-rtags) we have to reimplement the same functionality what you already have in rtags.el.
It might be better to have the common code in the C/C++ code and that might be faster as well.

**Comment by Andersbakken** [comment]
I can see that. Part of the problem is that this has to be stateful since a
callgraph basically can be endless and generally we don't want to send the
info over unless that particular tree node has been expanded. I'll think
about it.

I'm perfectly willing to add anything that vim-rtags would need to
implement this but I'm doubtful that it can be easily moved to c++
altogether.

Anders

**Comment by Andersbakken** [comment]
Please reopen if there are feature requests relating to this issuel. As I said, anything that rtags-vim needs to implement this functionality I will gladly add.

**Comment by andno037** [comment]
Do I miss something or does the rtags-references-tree not simply find all the references of a function, it won't actually find all the calling functions?
