### ISSUE TITLE
How to support cross compilation

### ISSUE THREAD

**Issue by baolonglin** [Andersbakken/rtags#887]
I have one linux machine, default gcc version is 4.3.4, the project like rtags need compiler >4.8, i install gcc 6.2.0 at /app/gcc/6.2.0. I use cmake command to generate makefiles and compile_commands.json:
`cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_C_COMPILER=/app/gcc/6.2.0/bin/gcc -DCMAKE_CXX_COMPILER=/app/gcc/6.2.0/bin/g++ ..`
compile success and the compile_commands file looks like:
`[
{
  "directory": "/workspace/testproject/build/src",
  "command": "/app/gcc/6.2.0/bin/g++      -o CMakeFiles/test.dir/main.cpp.o -c /workspace/testproject/src/main.cpp",
  "file": "/workspace/testproject/src/main.cpp"
}
]`

Then i use rc -J to generate the index, but i got syntax error at rdm side(c++11 not support by gcc4.3.4 default), use rc -s, it looks like rdm use the gcc 4.3.4 include header to solve the dependency.

Is that possible use the compile gcc version(which inside the compile commands json file) to solve the dependency? I try to add -I in rdm, it doesn't help.

**Comment by baolonglin** [comment]
I saw there is -R option, it doesn't work right now, i'm trying to collect more information

**Comment by baolonglin** [comment]
CompilerManager looks fine, find the correct include dependencies, but rp returns compile error, i'll check the code, if anyone know the reason, kindly tell me

**Comment by Andersbakken** [comment]
Hi Robin

Sorry about the delay.

I think the issue is that your clang doesn't pick up the 6.2 c++ headers.

Where do you get your clang from?

When I run:

$ clang -v

I get this output:

 (master)[src_rtags][abakken@fons:~/dev/rtags] clang -v
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/5.4.0
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/6.0.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6.0.0
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6.0.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.0.0
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64

My suspicion is that your clang only finds your 4.3.2 install of gcc. I'd
kinda recommend installing gcc/clang through your package system if at all
possible. I'm not 100% sure how clang determines where to find the gcc
includepaths on linux but there are some heuristics that likely do not
include looking in /app/gcc/6.2.0/ :-)

Anders

**Comment by baolonglin** [comment]
Hi Anders,

Thank you for your reply, and I think you are right. I'm using one clang(3.8) which compiled and installed under /app/clang/3.8. The clang default choose the 4.3.2.

After i add gcc-toolchain and std option to clang, it can compile success. Anyway, it was caused by my environment.

Thank you very much and i close this issue.

Robin

**Comment by skt041959** [comment]
@baolonglin Would you please tell me, how could you run rdm with the `toolchain` option or `CompilerManager` option to point the include path to gcc 6.2?

**Comment by baolonglin** [comment]
@skt041959 Sorry for late reply. use -R option to start the rdm. What i remembered now is using "--gcc-toolchain=<value> Use the gcc toolchain at the given directory", let clang find the correct gcc, in my example above, i also need to add std option to let clang enable c++11.
