### ISSUE TITLE
How to make flycheck-rtags support c++-14?

### ISSUE THREAD

**Issue by enzochiau** [Andersbakken/rtags#892]
When I use flycheck-rtags, I have the error as below:

    Semantic Issue: 'auto' not allowed in lambda parameter

I think that's a syntax supported in C++14. So how could I make flycheck-rtags support it?

**Comment by cslux** [comment]
Hey @enzochiau,

well, you could write a error filter function and assign it to `flycheck-rtags-error-filter`.

**Comment by cslux** [comment]
I tried it right now, and it turned out. It doesn't work as I thought to be.

This was my filter function assigned to `flycheck-rtags-error-filter`
``` emacs-lisp
(defun my-flycheck-rtags-error-filter (errors)
  "Function to filter out errors."
  (let (new-errors)
    (seq-do (lambda (err)
              (unless (string-match
                       "Semantic Issue: 'auto' not allowed in lambda parameter"
                       (flycheck-error-message err))
                (push err new-errors))
              (message "%s" (flycheck-error-message err)))
            errors)
    new-errors))
```

The error message is indeed removed from `flycheck-rtags` (flycheck) but the underlining is still visible as it is done by `rtags.el` also the error is still visible in *RTags Diagnostices* buffer. In short, it works partly. In my opinion it would be best to add the possibility to filter diagnostics in `rtags.el` before calling `flycheck-buffer` of course this would make `flycheck-rtags-error-filter` defcustom superfluous.

regards,
Christian

**Comment by Andersbakken** [comment]
My suspicion is that -std=c++14 isn't passed explicitly to clang and since gcc defaults to -std=c++14 this triggers an issue for libclang. Are you able to modify the build system to pass -std=c++14?

**Comment by cslux** [comment]
Closing this issue in favour of #893
