### ISSUE TITLE
Rtags does not index projects at all

### ISSUE THREAD

**Issue by sdeber** [Andersbakken/rtags#939]
I found a weird issue with the structure of my projects. I have three cmake projects A, B and C, where A is an application, B and C are libraries. They have dependencies like this: A is dependent on both B and C. And B is also dependent on C. When I try to use Rtags to index all these three projects, only B will be indexed. The other two seemed to be processed by Rtags (judging from the logs), however, if I do "rc --project", then it shows only project B.

**Comment by Andersbakken** [comment]
Hi

The issue is most likely that they all get folded into the A project.

Can you try this:

rc --sources

And see if you see the sources for B and C in there?

I'm assuming you build all at the same time using add_subdirectory? If so,
all the source files end up in A's compile_commands.json.

Can you check if this is the case?

regards

Anders

**Comment by sdeber** [comment]
Yes, you are right. I have checked with your method, and Rtags folded all sources into project B, not project A. Is there any rules about this kind of situation?

**Comment by Andersbakken** [comment]
Sorry. I completely forgot about this. In short the directory value for each source file will be used when finding the project. 

You could grep out the commands from the compile_commands.json file and index each of those lines separately using rc -c. I think this would create separate projects.
