### ISSUE TITLE
"Args out of range" error message from rtags-find-symbol-at-point when helm is in use

### ISSUE THREAD

**Issue by vibrys** [Andersbakken/rtags#978]
### Please mark appropriate
 - [* ] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [* ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description
While helm is in use, call to rtags-find-symbol-at-point for mst_elem_index fails with following error message:

```Args out of range: "      } __info;", 7, 21```

Code snippet looks like following:

```
#include <iostream>


#ifdef __KERNEL__
some lines are
comming here
#endif

typedef struct mystruct_elem_info
{
    struct
    {
        int                  __mst_elem_index;
    } __info;
} mystruct_elem_info_t;

#define mst_elem_index      __info.__mst_elem_index


int main()
{
  mystruct_elem_info_t info;
  std::cout << info.mst_elem_index << std::endl;
  std::cout << info.mst_elem_index << std::endl;
  return 0;
}
```

#### Expected behavior

mst_elem_index definition should be visited instead

#### Tips.
Immediate reason for error is that backend retuns two locations for definition, the first, correct one and the second, not so good, located in the line:
```    } __info;```
In next step, helm-rtags-transform tries to highlight mst_elem_index for the user convinience. It blindly assumes that this string is within the line, while it is not true. Thus following line produces "Args out of range", because it goes out of bounds:
```(content-token (substring content token-begin token-end))```

But probably the real reason is elsewhere  (only my guess).
```__KERNEL__``` is not defined during compilation, and lines under it ?are removed? just before passing file contents, so the resulted line number does not hit the correct line number.

If this is a true, then probably the problem could affect non-helm configs as well.

### Environment
- Your operating system:
   CentOs7

- LLVM/Clang version:
  4.0.0

- Rtags:
  499db6f

**Comment by rswarbrick-argon** [comment]
I can also reproduce this error by using `rtags-find-all-references-at-point` on the definition of a function. I'm not sure whether something deeper is broken, but to avoid the error (and make the functionality usable), you can change `helm-rtags-transform` so that `token-end` is computed like so:

      (let* ((file-name (match-string 1 line))
             (line-num (match-string 2 line))
             (column-num (match-string 3 line))
             (content (match-string 4 line))
             (token-begin (string-to-number column-num))
             (token-end (min (+ token-begin (length helm-rtags-token))
                             (length content)))
             (content-prefix (substring content 0 token-begin))
             (content-token (substring content token-begin token-end))
             (content-suffix (substring content token-end (length content))))

The main change is to use the `min` call, but you also have to shuffle the order of initialisers slightly so that `content` has been defined in time.

**Comment by thisEric** [comment]
@rswarbrick-argon , I have met the same issue, however this workaround doesn't work for me

**Comment by Andersbakken** [comment]
I can't quite seem to reproduce this. 

I've done the following: 

index the attached file:

(setq rtags-display-result-backend 'helm)
(goto-char 230)
(rtags-find-references-at-point)

and 

(goto-char 292)
(rtags-find-all-references-at-point)

Everything works as expected. I'm running on Mac OS X using emacs-plus from homebrew (25.5.1), llvm (4.0.1) from homebrew. 

I applied the proposed patch from above since it seems completely safe. @thisEric Can you check with the updated rtags whether this issue still happens and if so, send me the complete stack trace? 

E.g.

Make sure you do this first:
 (setq debug-on-error t)

**Comment by vibrys** [comment]
@Andersbakken, I installed db1244c and it does the job with my initial code snippet.

Thank You.

**Comment by vibrys** [comment]
also works with large code

regards,
Vibrys
