### ISSUE TITLE
navigation issue when source file uses types defined in files not "#included" by this source file

### ISSUE THREAD

**Issue by vibrys** [Andersbakken/rtags#980]
### Please mark appropriate
 - [ *] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [* ] rtags.el

### Problem description
code snippet looks like following:

myInclude.h:

```
static inline void my_fun()
{
  std::vector<int> vector;
  vector.push_back(10);
}
```

main.cpp:
```
#include <vector>

#include "myInclude.h"

int main()
{
  my_fun();
  return 0;
}
```

when pointing at my_fun() call, rtags finds the definition, but while pointing at push_back() call, the definition is not found.

#### Expected behavior
push_back() definition should be found.

### Environment
- Your operating system:
  CentOs7

- LLVM/Clang version:
  4.0.0

- rtags:
  499db6f

**Comment by Andersbakken** [comment]
We base our searches for symbols on the dependencies of the file the symbol is in and since this file doesn't include <vector> we don't look in that header for push_back.

I added something that will fall back if it doesn't find anything in the deps though. There's a chance this causes rtags to be slower on large projects but it should only be for queries that would fail anyway so I hope it's okay.

This should fix the example you posted.
